[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nwsc"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
exclude = [""]
namespaces = true

[project.scripts]
nwsc = "nwsc.main:main"
